# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='upper most latitude')),
                ('longitude', models.FloatField(help_text='left most longitude')),
                ('picture', models.CharField(max_length=100, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('solvers', models.TextField()),
            ],
        ),
    ]
