# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the location/puzzle', max_length=20, unique=True)),
                ('latitude', models.FloatField(help_text='upper most latitude')),
                ('longitude', models.FloatField(help_text='left most longitude')),
                ('picture', models.CharField(help_text='name of picture', max_length=100, unique=True)),
                ('completed', models.BooleanField(default=False, help_text='True if puzzle is completed, false if incomplete')),
                ('solvers', models.TextField(blank=True, help_text='users who have solved the puzzle', null=True)),
            ],
        ),
    ]
