# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umdPuzzle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='picture',
            field=models.CharField(help_text='name of picture', max_length=100),
        ),
    ]
